[supervisord]
loglevel=debug
logfile=/dev/stdout
logfile_maxbytes=0

[program:glycerine]
command=/usr/bin/glycerine enclave --bootstrap-vsock-address 3:2000 --egress_netfilter-queue-number 10 --egress-vsock-address 3:3000 --ingress-vsock-address 0:4000
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0

[program:sshd]
command=/usr/bin/start-sshd.sh
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
